# Alacritty Configuration - Matching Ghostty Setup
# Configuration for homelab work and infrastructure monitoring

# Import the Catppuccin Mocha theme
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
# Set TERM for SSH compatibility
TERM = "xterm-256color"

[window]
# Window padding (equivalent to Ghostty's window-padding-x/y = 10)
padding = { x = 10, y = 10 }
# Window decorations (equivalent to Ghostty's window-decoration = true)
decorations = "full"
# Start maximized for better monitoring visibility
startup_mode = "Windowed"
# Window opacity
opacity = 1.0

[font]
# Font configuration optimized for server monitoring (same as Ghostty)
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
size = 13.0

[cursor]
# Cursor configuration (equivalent to Ghostty's cursor settings)
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[selection]
# Copy on select (equivalent to Ghostty's copy-on-select = true)
save_to_clipboard = true

[shell]
# Shell integration with zsh
program = "/bin/zsh"
args = ["--login"]

[mouse]
# Mouse configuration for better UX
hide_when_typing = false

[keyboard]
# Key bindings for macOS (equivalent to Ghostty's macos-option-as-alt = true)
bindings = [
    # Option as Alt for better compatibility
    { key = "A", mods = "Alt", chars = "\u001ba" },
    { key = "B", mods = "Alt", chars = "\u001bb" },
    { key = "C", mods = "Alt", chars = "\u001bc" },
    { key = "D", mods = "Alt", chars = "\u001bd" },
    { key = "E", mods = "Alt", chars = "\u001be" },
    { key = "F", mods = "Alt", chars = "\u001bf" },
    { key = "G", mods = "Alt", chars = "\u001bg" },
    { key = "H", mods = "Alt", chars = "\u001bh" },
    { key = "I", mods = "Alt", chars = "\u001bi" },
    { key = "J", mods = "Alt", chars = "\u001bj" },
    { key = "K", mods = "Alt", chars = "\u001bk" },
    { key = "L", mods = "Alt", chars = "\u001bl" },
    { key = "M", mods = "Alt", chars = "\u001bm" },
    { key = "N", mods = "Alt", chars = "\u001bn" },
    { key = "O", mods = "Alt", chars = "\u001bo" },
    { key = "P", mods = "Alt", chars = "\u001bp" },
    { key = "Q", mods = "Alt", chars = "\u001bq" },
    { key = "R", mods = "Alt", chars = "\u001br" },
    { key = "S", mods = "Alt", chars = "\u001bs" },
    { key = "T", mods = "Alt", chars = "\u001bt" },
    { key = "U", mods = "Alt", chars = "\u001bu" },
    { key = "V", mods = "Alt", chars = "\u001bv" },
    { key = "W", mods = "Alt", chars = "\u001bw" },
    { key = "X", mods = "Alt", chars = "\u001bx" },
    { key = "Y", mods = "Alt", chars = "\u001by" },
    { key = "Z", mods = "Alt", chars = "\u001bz" },
]