#!/usr/bin/env bash
# =============================================================================
# CHOOSE-YOU - Interactive Cloud-Init Generator
# =============================================================================
# "I choose you!" - Generate cloud-init configs for VMs
#
# Creates cloud-init YAML with:
# - Tailscale auto-provisioning
# - Portable dotfiles
# - SSH keys
# - Custom packages

set -euo pipefail

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${PURPLE}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${PURPLE}║        ⚡ CHOOSE-YOU! Cloud-Init Generator            ║${NC}"
echo -e "${PURPLE}║        Create VMs that auto-join your Tailnet          ║${NC}"
echo -e "${PURPLE}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Gather information
echo -e "${CYAN}Let's configure your VM!${NC}"
echo ""

read -p "$(echo -e ${BLUE}📛 VM hostname:${NC} )" HOSTNAME
read -p "$(echo -e ${BLUE}🔑 Tailscale auth key:${NC} )" AUTHKEY
read -p "$(echo -e ${BLUE}🏷️  Tailscale tags [tag:vm,tag:cloud-init]:${NC} )" TAGS
TAGS=${TAGS:-tag:vm,tag:cloud-init}

read -p "$(echo -e ${BLUE}👤 Username [kellen]:${NC} )" USERNAME
USERNAME=${USERNAME:-kellen}

read -p "$(echo -e ${BLUE}🔐 SSH public key path [~/.ssh/id_ed25519.pub]:${NC} )" SSH_KEY_PATH
SSH_KEY_PATH=${SSH_KEY_PATH:-~/.ssh/id_ed25519.pub}
SSH_KEY_PATH="${SSH_KEY_PATH/#\~/$HOME}"

if [[ ! -f "$SSH_KEY_PATH" ]]; then
    echo -e "${YELLOW}⚠️  SSH key not found at $SSH_KEY_PATH${NC}"
    read -p "$(echo -e ${BLUE}Enter SSH public key manually:${NC} )" SSH_KEY_MANUAL
    SSH_KEY="$SSH_KEY_MANUAL"
else
    SSH_KEY=$(cat "$SSH_KEY_PATH")
fi

read -p "$(echo -e ${BLUE}🌍 Timezone [America/Los_Angeles]:${NC} )" TIMEZONE
TIMEZONE=${TIMEZONE:-America/Los_Angeles}

read -p "$(echo -e ${BLUE}📦 Install portable dotfiles? [Y/n]:${NC} )" INSTALL_DOTFILES
INSTALL_DOTFILES=${INSTALL_DOTFILES:-Y}

read -p "$(echo -e ${BLUE}📄 Output file [cloud-init-${HOSTNAME}.yaml]:${NC} )" OUTPUT_FILE
OUTPUT_FILE=${OUTPUT_FILE:-cloud-init-${HOSTNAME}.yaml}

echo ""
echo -e "${GREEN}✨ Generating cloud-init config...${NC}"

# Generate cloud-init YAML
cat > "$OUTPUT_FILE" << EOF
#cloud-config
# =============================================================================
# Generated by CHOOSE-YOU! 🎯
# Hostname: $HOSTNAME
# Generated: $(date)
# =============================================================================

# Set hostname
hostname: $HOSTNAME
fqdn: ${HOSTNAME}.local

# System packages
packages:
  - curl
  - git
  - vim
  - htop
  - ncdu
  - tmux

# Run commands on first boot
runcmd:
  # Install Tailscale
  - curl -fsSL https://tailscale.com/install.sh | sh

  # Authenticate with Tailnet
  - |
    tailscale up \\
      --authkey=${AUTHKEY} \\
      --hostname=${HOSTNAME} \\
      --advertise-tags=${TAGS} \\
      --ssh

EOF

# Add dotfiles installation if requested
if [[ "$INSTALL_DOTFILES" =~ ^[Yy] ]]; then
    cat >> "$OUTPUT_FILE" << 'EOF'
  # Install portable dotfiles
  - curl -fsSL https://raw.githubusercontent.com/UncertainMeow/dotfiles/main/bootstrap-portable.sh | bash

EOF
fi

# Continue with rest of config
cat >> "$OUTPUT_FILE" << EOF
  # Set timezone
  - timedatectl set-timezone $TIMEZONE

  # Display info
  - echo "✅ VM provisioned successfully!" > /etc/motd
  - echo "Hostname: $HOSTNAME" >> /etc/motd
  - echo "Tailscale: Connected" >> /etc/motd

# Create user
users:
  - name: $USERNAME
    groups: [sudo, docker]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/zsh
    ssh_authorized_keys:
      - $SSH_KEY

# Security - disable root password login
ssh_pwauth: false
disable_root: true

# Final setup message
final_message: |
  ╔══════════════════════════════════════════════════════════╗
  ║        ⚡ Cloud-Init Complete!                          ║
  ║        VM: $HOSTNAME                                      ║
  ║        Status: Connected to Tailnet                     ║
  ╚══════════════════════════════════════════════════════════╝

  Access via Tailscale:
    ssh $USERNAME@$HOSTNAME

# Reboot after provisioning (optional)
power_state:
  mode: reboot
  delay: now
  message: "Provisioning complete - rebooting"
  condition: true
EOF

echo -e "${GREEN}✅ Cloud-init config created: ${CYAN}$OUTPUT_FILE${NC}"
echo ""
echo -e "${YELLOW}📋 Next steps:${NC}"
echo -e "  ${BLUE}1.${NC} Review the config: ${CYAN}cat $OUTPUT_FILE${NC}"
echo -e "  ${BLUE}2.${NC} Use with Proxmox, VMware, AWS, GCP, Azure, etc."
echo -e "  ${BLUE}3.${NC} VM will auto-configure and join your Tailnet on first boot!"
echo ""
echo -e "${YELLOW}💡 Proxmox example:${NC}"
echo -e "  ${CYAN}qm set <vmid> --cicustom user=local:snippets/$OUTPUT_FILE${NC}"
echo ""
