#!/usr/bin/env bash
# =============================================================================
# GO-DOCKAHU - Docker Compose + Tailscale Generator
# =============================================================================
# "Go Pikachu!" - Generate Docker Compose files with Tailscale sidecars
#
# Creates docker-compose.yaml with:
# - Tailscale sidecar containers
# - Your application containers
# - Proper networking

set -euo pipefail

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${YELLOW}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${YELLOW}║        ⚡ GO-DOCKAHU! Docker Compose Generator         ║${NC}"
echo -e "${YELLOW}║        Containers that auto-join your Tailnet          ║${NC}"
echo -e "${YELLOW}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Service types
echo -e "${CYAN}What type of service?${NC}"
echo "  1) Web application (nginx, node, python, etc.)"
echo "  2) Database (postgres, mysql, redis, etc.)"
echo "  3) Monitoring (grafana, prometheus, etc.)"
echo "  4) Custom (specify image)"
echo ""
read -p "$(echo -e ${BLUE}Choice [1]:${NC} )" SERVICE_TYPE
SERVICE_TYPE=${SERVICE_TYPE:-1}

# Gather info
read -p "$(echo -e ${BLUE}📛 Service name [my-app]:${NC} )" SERVICE_NAME
SERVICE_NAME=${SERVICE_NAME:-my-app}

read -p "$(echo -e ${BLUE}🐋 Docker image:${NC} )" DOCKER_IMAGE

read -p "$(echo -e ${BLUE}🏷️  Tailscale tags [tag:container,tag:docker]:${NC} )" TS_TAGS
TS_TAGS=${TS_TAGS:-tag:container,tag:docker}

read -p "$(echo -e ${BLUE}🔌 Expose port(s) locally? [none/8080/...]:${NC} )" LOCAL_PORTS
LOCAL_PORTS=${LOCAL_PORTS:-none}

read -p "$(echo -e ${BLUE}💾 Need persistent volume? [y/N]:${NC} )" NEED_VOLUME
NEED_VOLUME=${NEED_VOLUME:-N}

if [[ "$NEED_VOLUME" =~ ^[Yy] ]]; then
    read -p "$(echo -e ${BLUE}📁 Volume mount path in container:${NC} )" VOLUME_PATH
fi

read -p "$(echo -e ${BLUE}📄 Output file [docker-compose-${SERVICE_NAME}.yaml]:${NC} )" OUTPUT_FILE
OUTPUT_FILE=${OUTPUT_FILE:-docker-compose-${SERVICE_NAME}.yaml}

echo ""
echo -e "${GREEN}✨ Generating Docker Compose config...${NC}"

# Generate docker-compose.yaml
cat > "$OUTPUT_FILE" << 'EOF'
version: '3.8'

# =============================================================================
# Generated by GO-DOCKAHU! ⚡
EOF

cat >> "$OUTPUT_FILE" << EOF
# Service: $SERVICE_NAME
# Generated: $(date)
# =============================================================================

services:
  # Tailscale sidecar for $SERVICE_NAME
  ${SERVICE_NAME}-tailscale:
    image: tailscale/tailscale:latest
    hostname: $SERVICE_NAME
    container_name: ${SERVICE_NAME}-tailscale
    environment:
      - TS_AUTHKEY=\${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=$SERVICE_NAME
      - TS_EXTRA_ARGS=--advertise-tags=${TS_TAGS} --ssh
    volumes:
      - ${SERVICE_NAME}-tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    networks:
      - tailnet

  # Your application
  ${SERVICE_NAME}:
    image: $DOCKER_IMAGE
    container_name: $SERVICE_NAME
    depends_on:
      - ${SERVICE_NAME}-tailscale
    network_mode: service:${SERVICE_NAME}-tailscale  # Share network with Tailscale
EOF

# Add ports if specified
if [[ "$LOCAL_PORTS" != "none" ]] && [[ -n "$LOCAL_PORTS" ]]; then
    cat >> "$OUTPUT_FILE" << EOF
    ports:
      - "$LOCAL_PORTS:$LOCAL_PORTS"
EOF
fi

# Add volume if needed
if [[ "$NEED_VOLUME" =~ ^[Yy] ]]; then
    cat >> "$OUTPUT_FILE" << EOF
    volumes:
      - ${SERVICE_NAME}-data:$VOLUME_PATH
EOF
fi

# Add environment variables section
cat >> "$OUTPUT_FILE" << EOF
    environment:
      # Add your environment variables here
      - NODE_ENV=production
EOF

# Finish the file
cat >> "$OUTPUT_FILE" << EOF
    restart: unless-stopped

volumes:
  ${SERVICE_NAME}-tailscale-state:
EOF

if [[ "$NEED_VOLUME" =~ ^[Yy] ]]; then
    cat >> "$OUTPUT_FILE" << EOF
  ${SERVICE_NAME}-data:
EOF
fi

cat >> "$OUTPUT_FILE" << EOF

networks:
  tailnet:
    driver: bridge

# =============================================================================
# USAGE
# =============================================================================
# 1. Create .env file with:
#    TAILSCALE_AUTHKEY=tskey-auth-xxxxx
#
# 2. Generate auth key at: https://login.tailscale.com/admin/settings/keys
#    - Enable "Reusable" and "Ephemeral" for containers
#    - Add tags matching TS_EXTRA_ARGS above
#
# 3. Deploy:
#    docker-compose -f $OUTPUT_FILE up -d
#
# 4. Access from any Tailnet device:
#    http://$SERVICE_NAME
#    (or whatever protocol your service uses)
#
# 5. SSH into container (if --ssh enabled):
#    ssh $SERVICE_NAME
#
# 6. Check logs:
#    docker-compose -f $OUTPUT_FILE logs -f
#
# 7. Stop:
#    docker-compose -f $OUTPUT_FILE down
#
# =============================================================================
EOF

echo -e "${GREEN}✅ Docker Compose config created: ${CYAN}$OUTPUT_FILE${NC}"
echo ""
echo -e "${YELLOW}📋 Next steps:${NC}"
echo -e "  ${BLUE}1.${NC} Create .env file:"
echo -e "     ${CYAN}echo 'TAILSCALE_AUTHKEY=tskey-auth-YOUR_KEY_HERE' > .env${NC}"
echo ""
echo -e "  ${BLUE}2.${NC} Deploy:"
echo -e "     ${CYAN}docker-compose -f $OUTPUT_FILE up -d${NC}"
echo ""
echo -e "  ${BLUE}3.${NC} Access from Tailnet:"
echo -e "     ${CYAN}curl http://$SERVICE_NAME${NC}"
echo -e "     ${CYAN}ssh $SERVICE_NAME${NC}"
echo ""
echo -e "${YELLOW}💡 Tip:${NC} Generate ephemeral auth keys for containers at:"
echo -e "   ${CYAN}https://login.tailscale.com/admin/settings/keys${NC}"
echo ""
